# This class contains the map data in the game, and some scripting to compile it to a valid 
# jsonb-column storable format. Digitizing the map data by hand was easiest by going column-
# wise and not writing all the hex hashes by hand, so thats why if you are wondering.
class GameMap
  def self.parse_map_data
    map = TYPE_BY_COLUMN.reduce({}) do |hexes, (col, types)|
      types.each_with_index do |type, i|
        cost = COST_BY_COLUMN[col][i]
        hexes.store(col+i.to_s, {type: type, cost: cost})
      end 
      hexes
    end
    map.reject! { |hex, data| data[:type] == :empty }
    map = { hexes: map }
    map[:companies] = COMPANIES
    map[:hexes]['R5'][:built]=['red']
    map[:hexes]['Q7'][:built]=['blue']
    map[:hexes]['S3'][:built]=['green']
    map[:hexes]['Q9'][:built]=['yellow']

    pp map
  end

  COMPANIES = {
    red: { started: true, money: 0, shares: 3, track: 19, start_hex: 'R5' },
    blue: { started: true, money: 0, shares: 4, track: 21, start_hex: 'Q7'},
    green: { started: true, money: 0, shares: 5, track: 23, start_hex: 'S3'},
    yellow: { started: true, money: 0, shares: 6, track: 25, start_hex: 'Q9'},
    black: { started: false, money: 0, shares: 2, track: 11, start_Hex: 'D3'}
  }

  TYPE_BY_COLUMN = 
    {'A'=> %i[empty empty town field field],
    'B'=> %i[empty empty field field field town field],
    'C'=> %i[field field town field field field field field],
    'D'=> %i[field field field town field field field town],
    'E'=> %i[city field field field field field field field field],
    'F'=> %i[empty town field field field town field field town],
    'G'=> %i[empty empty field field field field field field forest mountain], 
    'H'=> %i[empty empty field field field field field forest forest mountain],
    'I'=> %i[empty empty town field town forest city forest mountain town mountain],
    'J'=> %i[empty field forest forest forest forest mountain mountain mountain mountain],
    'K'=> %i[empty field forest forest city forest mountain town mountain forest town],
    'L'=> %i[town field forest forest mountain mountain mountain forest forest field],
    'M'=> %i[field forest forest forest town mountain mountain forest forest forest town],
    'N'=> %i[field forest forest forest mountain forest town forest field field],
    'O'=> %i[town forest forest forest town field field field field forest town],
    'P'=> %i[field forest forest forest field field field field field field],
    'Q'=> %i[town forest forest town forest field field town field town],
    'R'=> %i[field forest forest forest field town field],
    'S'=> %i[town field field town field field]}

    COST_BY_COLUMN = {
     'A'=> %w[e e 3 1 1],
     'B'=> %w[e e 1 1 1 1 1], 
     'C'=> %w[1 1 2 1 1 1 1 1],
     'D'=> %w[1 1 1 1 1 1 1 2],
     'E'=> %w[3 1 1 1 1 1 1 1 1],
     'F'=> %w[e 2 1 1 1 1 1 1 2],
     'G'=> %w[e e 1 1 1 1 1 1 2 3],
     'H'=> %w[e e 1 1 1 1 1 2 2 3],
     'I'=> %w[e e 1 1 2 2 3 2 4 3 3],
     'J'=> %w[e 1 1 2 2 2 3 4 4 3],
     'K'=> %w[e 1 2 4 4 4 4 2 4 2 2],
     'L'=> %w[2 1 2 3 3 4 2 3 2 1],
     'M'=> %w[1 2 2 3 2 4 2 2 2 2 1],
     'N'=> %w[1 3 3 2 3 4 2 2 2 1],
     'O'=> %w[2 2 3 3 2 2 2 1 2 2 2],
     'P'=> %w[1 2 2 2 1 1 1 1 1 1],
     'Q'=> %w[2 2 2 2 2 1 1 0 1 0],
     'R'=> %w[1 2 2 2 1 0 1],
     'S'=> %w[2 1 1 0 1 1]}

    # calculated with parse_map_data
    MAP_DATA = {:hexes=>
  {"A2"=>{:type=>:town, :cost=>"3"},
   "A3"=>{:type=>:field, :cost=>"1"},
   "A4"=>{:type=>:field, :cost=>"1"},
   "B2"=>{:type=>:field, :cost=>"1"},
   "B3"=>{:type=>:field, :cost=>"1"},
   "B4"=>{:type=>:field, :cost=>"1"},
   "B5"=>{:type=>:town, :cost=>"1"},
   "B6"=>{:type=>:field, :cost=>"1"},
   "C0"=>{:type=>:field, :cost=>"1"},
   "C1"=>{:type=>:field, :cost=>"1"},
   "C2"=>{:type=>:town, :cost=>"2"},
   "C3"=>{:type=>:field, :cost=>"1"},
   "C4"=>{:type=>:field, :cost=>"1"},
   "C5"=>{:type=>:field, :cost=>"1"},
   "C6"=>{:type=>:field, :cost=>"1"},
   "C7"=>{:type=>:field, :cost=>"1"},
   "D0"=>{:type=>:field, :cost=>"1"},
   "D1"=>{:type=>:field, :cost=>"1"},
   "D2"=>{:type=>:field, :cost=>"1"},
   "D3"=>{:type=>:town, :cost=>"1"},
   "D4"=>{:type=>:field, :cost=>"1"},
   "D5"=>{:type=>:field, :cost=>"1"},
   "D6"=>{:type=>:field, :cost=>"1"},
   "D7"=>{:type=>:town, :cost=>"2"},
   "E0"=>{:type=>:city, :cost=>"3"},
   "E1"=>{:type=>:field, :cost=>"1"},
   "E2"=>{:type=>:field, :cost=>"1"},
   "E3"=>{:type=>:field, :cost=>"1"},
   "E4"=>{:type=>:field, :cost=>"1"},
   "E5"=>{:type=>:field, :cost=>"1"},
   "E6"=>{:type=>:field, :cost=>"1"},
   "E7"=>{:type=>:field, :cost=>"1"},
   "E8"=>{:type=>:field, :cost=>"1"},
   "F1"=>{:type=>:town, :cost=>"2"},
   "F2"=>{:type=>:field, :cost=>"1"},
   "F3"=>{:type=>:field, :cost=>"1"},
   "F4"=>{:type=>:field, :cost=>"1"},
   "F5"=>{:type=>:town, :cost=>"1"},
   "F6"=>{:type=>:field, :cost=>"1"},
   "F7"=>{:type=>:field, :cost=>"1"},
   "F8"=>{:type=>:town, :cost=>"2"},
   "G2"=>{:type=>:field, :cost=>"1"},
   "G3"=>{:type=>:field, :cost=>"1"},
   "G4"=>{:type=>:field, :cost=>"1"},
   "G5"=>{:type=>:field, :cost=>"1"},
   "G6"=>{:type=>:field, :cost=>"1"},
   "G7"=>{:type=>:field, :cost=>"1"},
   "G8"=>{:type=>:forest, :cost=>"2"},
   "G9"=>{:type=>:mountain, :cost=>"3"},
   "H2"=>{:type=>:field, :cost=>"1"},
   "H3"=>{:type=>:field, :cost=>"1"},
   "H4"=>{:type=>:field, :cost=>"1"},
   "H5"=>{:type=>:field, :cost=>"1"},
   "H6"=>{:type=>:field, :cost=>"1"},
   "H7"=>{:type=>:forest, :cost=>"2"},
   "H8"=>{:type=>:forest, :cost=>"2"},
   "H9"=>{:type=>:mountain, :cost=>"3"},
   "I2"=>{:type=>:town, :cost=>"1"},
   "I3"=>{:type=>:field, :cost=>"1"},
   "I4"=>{:type=>:town, :cost=>"2"},
   "I5"=>{:type=>:forest, :cost=>"2"},
   "I6"=>{:type=>:city, :cost=>"3"},
   "I7"=>{:type=>:forest, :cost=>"2"},
   "I8"=>{:type=>:mountain, :cost=>"4"},
   "I9"=>{:type=>:town, :cost=>"3"},
   "I10"=>{:type=>:mountain, :cost=>"3"},
   "J1"=>{:type=>:field, :cost=>"1"},
   "J2"=>{:type=>:forest, :cost=>"1"},
   "J3"=>{:type=>:forest, :cost=>"2"},
   "J4"=>{:type=>:forest, :cost=>"2"},
   "J5"=>{:type=>:forest, :cost=>"2"},
   "J6"=>{:type=>:mountain, :cost=>"3"},
   "J7"=>{:type=>:mountain, :cost=>"4"},
   "J8"=>{:type=>:mountain, :cost=>"4"},
   "J9"=>{:type=>:mountain, :cost=>"3"},
   "K1"=>{:type=>:field, :cost=>"1"},
   "K2"=>{:type=>:forest, :cost=>"2"},
   "K3"=>{:type=>:forest, :cost=>"4"},
   "K4"=>{:type=>:city, :cost=>"4"},
   "K5"=>{:type=>:forest, :cost=>"4"},
   "K6"=>{:type=>:mountain, :cost=>"4"},
   "K7"=>{:type=>:town, :cost=>"2"},
   "K8"=>{:type=>:mountain, :cost=>"4"},
   "K9"=>{:type=>:forest, :cost=>"2"},
   "K10"=>{:type=>:town, :cost=>"2"},
   "L0"=>{:type=>:town, :cost=>"2"},
   "L1"=>{:type=>:field, :cost=>"1"},
   "L2"=>{:type=>:forest, :cost=>"2"},
   "L3"=>{:type=>:forest, :cost=>"3"},
   "L4"=>{:type=>:mountain, :cost=>"3"},
   "L5"=>{:type=>:mountain, :cost=>"4"},
   "L6"=>{:type=>:mountain, :cost=>"2"},
   "L7"=>{:type=>:forest, :cost=>"3"},
   "L8"=>{:type=>:forest, :cost=>"2"},
   "L9"=>{:type=>:field, :cost=>"1"},
   "M0"=>{:type=>:field, :cost=>"1"},
   "M1"=>{:type=>:forest, :cost=>"2"},
   "M2"=>{:type=>:forest, :cost=>"2"},
   "M3"=>{:type=>:forest, :cost=>"3"},
   "M4"=>{:type=>:town, :cost=>"2"},
   "M5"=>{:type=>:mountain, :cost=>"4"},
   "M6"=>{:type=>:mountain, :cost=>"2"},
   "M7"=>{:type=>:forest, :cost=>"2"},
   "M8"=>{:type=>:forest, :cost=>"2"},
   "M9"=>{:type=>:forest, :cost=>"2"},
   "M10"=>{:type=>:town, :cost=>"1"},
   "N0"=>{:type=>:field, :cost=>"1"},
   "N1"=>{:type=>:forest, :cost=>"3"},
   "N2"=>{:type=>:forest, :cost=>"3"},
   "N3"=>{:type=>:forest, :cost=>"2"},
   "N4"=>{:type=>:mountain, :cost=>"3"},
   "N5"=>{:type=>:forest, :cost=>"4"},
   "N6"=>{:type=>:town, :cost=>"2"},
   "N7"=>{:type=>:forest, :cost=>"2"},
   "N8"=>{:type=>:field, :cost=>"2"},
   "N9"=>{:type=>:field, :cost=>"1"},
   "O0"=>{:type=>:town, :cost=>"2"},
   "O1"=>{:type=>:forest, :cost=>"2"},
   "O2"=>{:type=>:forest, :cost=>"3"},
   "O3"=>{:type=>:forest, :cost=>"3"},
   "O4"=>{:type=>:town, :cost=>"2"},
   "O5"=>{:type=>:field, :cost=>"2"},
   "O6"=>{:type=>:field, :cost=>"2"},
   "O7"=>{:type=>:field, :cost=>"1"},
   "O8"=>{:type=>:field, :cost=>"2"},
   "O9"=>{:type=>:forest, :cost=>"2"},
   "O10"=>{:type=>:town, :cost=>"2"},
   "P0"=>{:type=>:field, :cost=>"1"},
   "P1"=>{:type=>:forest, :cost=>"2"},
   "P2"=>{:type=>:forest, :cost=>"2"},
   "P3"=>{:type=>:forest, :cost=>"2"},
   "P4"=>{:type=>:field, :cost=>"1"},
   "P5"=>{:type=>:field, :cost=>"1"},
   "P6"=>{:type=>:field, :cost=>"1"},
   "P7"=>{:type=>:field, :cost=>"1"},
   "P8"=>{:type=>:field, :cost=>"1"},
   "P9"=>{:type=>:field, :cost=>"1"},
   "Q0"=>{:type=>:town, :cost=>"2"},
   "Q1"=>{:type=>:forest, :cost=>"2"},
   "Q2"=>{:type=>:forest, :cost=>"2"},
   "Q3"=>{:type=>:town, :cost=>"2"},
   "Q4"=>{:type=>:forest, :cost=>"2"},
   "Q5"=>{:type=>:field, :cost=>"1"},
   "Q6"=>{:type=>:field, :cost=>"1"},
   "Q7"=>{:type=>:town, :cost=>"0"},
   "Q8"=>{:type=>:field, :cost=>"1"},
   "Q9"=>{:type=>:town, :cost=>"0"},
   "R0"=>{:type=>:field, :cost=>"1"},
   "R1"=>{:type=>:forest, :cost=>"2"},
   "R2"=>{:type=>:forest, :cost=>"2"},
   "R3"=>{:type=>:forest, :cost=>"2"},
   "R4"=>{:type=>:field, :cost=>"1"},
   "R5"=>{:type=>:town, :cost=>"0"},
   "R6"=>{:type=>:field, :cost=>"1"},
   "S0"=>{:type=>:town, :cost=>"2"},
   "S1"=>{:type=>:field, :cost=>"1"},
   "S2"=>{:type=>:field, :cost=>"1"},
   "S3"=>{:type=>:town, :cost=>"0"},
   "S4"=>{:type=>:field, :cost=>"1"},
   "S5"=>{:type=>:field, :cost=>"1"}}}

  MAP_WITH_COMPANIES = {:hexes=>
  {"A2"=>{:type=>:town, :cost=>"3"},
   "A3"=>{:type=>:field, :cost=>"1"},
   "A4"=>{:type=>:field, :cost=>"1"},
   "B2"=>{:type=>:field, :cost=>"1"},
   "B3"=>{:type=>:field, :cost=>"1"},
   "B4"=>{:type=>:field, :cost=>"1"},
   "B5"=>{:type=>:town, :cost=>"1"},
   "B6"=>{:type=>:field, :cost=>"1"},
   "C0"=>{:type=>:field, :cost=>"1"},
   "C1"=>{:type=>:field, :cost=>"1"},
   "C2"=>{:type=>:town, :cost=>"2"},
   "C3"=>{:type=>:field, :cost=>"1"},
   "C4"=>{:type=>:field, :cost=>"1"},
   "C5"=>{:type=>:field, :cost=>"1"},
   "C6"=>{:type=>:field, :cost=>"1"},
   "C7"=>{:type=>:field, :cost=>"1"},
   "D0"=>{:type=>:field, :cost=>"1"},
   "D1"=>{:type=>:field, :cost=>"1"},
   "D2"=>{:type=>:field, :cost=>"1"},
   "D3"=>{:type=>:town, :cost=>"1"},
   "D4"=>{:type=>:field, :cost=>"1"},
   "D5"=>{:type=>:field, :cost=>"1"},
   "D6"=>{:type=>:field, :cost=>"1"},
   "D7"=>{:type=>:town, :cost=>"2"},
   "E0"=>{:type=>:city, :cost=>"3"},
   "E1"=>{:type=>:field, :cost=>"1"},
   "E2"=>{:type=>:field, :cost=>"1"},
   "E3"=>{:type=>:field, :cost=>"1"},
   "E4"=>{:type=>:field, :cost=>"1"},
   "E5"=>{:type=>:field, :cost=>"1"},
   "E6"=>{:type=>:field, :cost=>"1"},
   "E7"=>{:type=>:field, :cost=>"1"},
   "E8"=>{:type=>:field, :cost=>"1"},
   "F1"=>{:type=>:town, :cost=>"2"},
   "F2"=>{:type=>:field, :cost=>"1"},
   "F3"=>{:type=>:field, :cost=>"1"},
   "F4"=>{:type=>:field, :cost=>"1"},
   "F5"=>{:type=>:town, :cost=>"1"},
   "F6"=>{:type=>:field, :cost=>"1"},
   "F7"=>{:type=>:field, :cost=>"1"},
   "F8"=>{:type=>:town, :cost=>"2"},
   "G2"=>{:type=>:field, :cost=>"1"},
   "G3"=>{:type=>:field, :cost=>"1"},
   "G4"=>{:type=>:field, :cost=>"1"},
   "G5"=>{:type=>:field, :cost=>"1"},
   "G6"=>{:type=>:field, :cost=>"1"},
   "G7"=>{:type=>:field, :cost=>"1"},
   "G8"=>{:type=>:forest, :cost=>"2"},
   "G9"=>{:type=>:mountain, :cost=>"3"},
   "H2"=>{:type=>:field, :cost=>"1"},
   "H3"=>{:type=>:field, :cost=>"1"},
   "H4"=>{:type=>:field, :cost=>"1"},
   "H5"=>{:type=>:field, :cost=>"1"},
   "H6"=>{:type=>:field, :cost=>"1"},
   "H7"=>{:type=>:forest, :cost=>"2"},
   "H8"=>{:type=>:forest, :cost=>"2"},
   "H9"=>{:type=>:mountain, :cost=>"3"},
   "I2"=>{:type=>:town, :cost=>"1"},
   "I3"=>{:type=>:field, :cost=>"1"},
   "I4"=>{:type=>:town, :cost=>"2"},
   "I5"=>{:type=>:forest, :cost=>"2"},
   "I6"=>{:type=>:city, :cost=>"3"},
   "I7"=>{:type=>:forest, :cost=>"2"},
   "I8"=>{:type=>:mountain, :cost=>"4"},
   "I9"=>{:type=>:town, :cost=>"3"},
   "I10"=>{:type=>:mountain, :cost=>"3"},
   "J1"=>{:type=>:field, :cost=>"1"},
   "J2"=>{:type=>:forest, :cost=>"1"},
   "J3"=>{:type=>:forest, :cost=>"2"},
   "J4"=>{:type=>:forest, :cost=>"2"},
   "J5"=>{:type=>:forest, :cost=>"2"},
   "J6"=>{:type=>:mountain, :cost=>"3"},
   "J7"=>{:type=>:mountain, :cost=>"4"},
   "J8"=>{:type=>:mountain, :cost=>"4"},
   "J9"=>{:type=>:mountain, :cost=>"3"},
   "K1"=>{:type=>:field, :cost=>"1"},
   "K2"=>{:type=>:forest, :cost=>"2"},
   "K3"=>{:type=>:forest, :cost=>"4"},
   "K4"=>{:type=>:city, :cost=>"4"},
   "K5"=>{:type=>:forest, :cost=>"4"},
   "K6"=>{:type=>:mountain, :cost=>"4"},
   "K7"=>{:type=>:town, :cost=>"2"},
   "K8"=>{:type=>:mountain, :cost=>"4"},
   "K9"=>{:type=>:forest, :cost=>"2"},
   "K10"=>{:type=>:town, :cost=>"2"},
   "L0"=>{:type=>:town, :cost=>"2"},
   "L1"=>{:type=>:field, :cost=>"1"},
   "L2"=>{:type=>:forest, :cost=>"2"},
   "L3"=>{:type=>:forest, :cost=>"3"},
   "L4"=>{:type=>:mountain, :cost=>"3"},
   "L5"=>{:type=>:mountain, :cost=>"4"},
   "L6"=>{:type=>:mountain, :cost=>"2"},
   "L7"=>{:type=>:forest, :cost=>"3"},
   "L8"=>{:type=>:forest, :cost=>"2"},
   "L9"=>{:type=>:field, :cost=>"1"},
   "M0"=>{:type=>:field, :cost=>"1"},
   "M1"=>{:type=>:forest, :cost=>"2"},
   "M2"=>{:type=>:forest, :cost=>"2"},
   "M3"=>{:type=>:forest, :cost=>"3"},
   "M4"=>{:type=>:town, :cost=>"2"},
   "M5"=>{:type=>:mountain, :cost=>"4"},
   "M6"=>{:type=>:mountain, :cost=>"2"},
   "M7"=>{:type=>:forest, :cost=>"2"},
   "M8"=>{:type=>:forest, :cost=>"2"},
   "M9"=>{:type=>:forest, :cost=>"2"},
   "M10"=>{:type=>:town, :cost=>"1"},
   "N0"=>{:type=>:field, :cost=>"1"},
   "N1"=>{:type=>:forest, :cost=>"3"},
   "N2"=>{:type=>:forest, :cost=>"3"},
   "N3"=>{:type=>:forest, :cost=>"2"},
   "N4"=>{:type=>:mountain, :cost=>"3"},
   "N5"=>{:type=>:forest, :cost=>"4"},
   "N6"=>{:type=>:town, :cost=>"2"},
   "N7"=>{:type=>:forest, :cost=>"2"},
   "N8"=>{:type=>:field, :cost=>"2"},
   "N9"=>{:type=>:field, :cost=>"1"},
   "O0"=>{:type=>:town, :cost=>"2"},
   "O1"=>{:type=>:forest, :cost=>"2"},
   "O2"=>{:type=>:forest, :cost=>"3"},
   "O3"=>{:type=>:forest, :cost=>"3"},
   "O4"=>{:type=>:town, :cost=>"2"},
   "O5"=>{:type=>:field, :cost=>"2"},
   "O6"=>{:type=>:field, :cost=>"2"},
   "O7"=>{:type=>:field, :cost=>"1"},
   "O8"=>{:type=>:field, :cost=>"2"},
   "O9"=>{:type=>:forest, :cost=>"2"},
   "O10"=>{:type=>:town, :cost=>"2"},
   "P0"=>{:type=>:field, :cost=>"1"},
   "P1"=>{:type=>:forest, :cost=>"2"},
   "P2"=>{:type=>:forest, :cost=>"2"},
   "P3"=>{:type=>:forest, :cost=>"2"},
   "P4"=>{:type=>:field, :cost=>"1"},
   "P5"=>{:type=>:field, :cost=>"1"},
   "P6"=>{:type=>:field, :cost=>"1"},
   "P7"=>{:type=>:field, :cost=>"1"},
   "P8"=>{:type=>:field, :cost=>"1"},
   "P9"=>{:type=>:field, :cost=>"1"},
   "Q0"=>{:type=>:town, :cost=>"2"},
   "Q1"=>{:type=>:forest, :cost=>"2"},
   "Q2"=>{:type=>:forest, :cost=>"2"},
   "Q3"=>{:type=>:town, :cost=>"2"},
   "Q4"=>{:type=>:forest, :cost=>"2"},
   "Q5"=>{:type=>:field, :cost=>"1"},
   "Q6"=>{:type=>:field, :cost=>"1"},
   "Q7"=>{:type=>:town, :cost=>"0", :built=>["blue"]},
   "Q8"=>{:type=>:field, :cost=>"1"},
   "Q9"=>{:type=>:town, :cost=>"0", :built=>["yellow"]},
   "R0"=>{:type=>:field, :cost=>"1"},
   "R1"=>{:type=>:forest, :cost=>"2"},
   "R2"=>{:type=>:forest, :cost=>"2"},
   "R3"=>{:type=>:forest, :cost=>"2"},
   "R4"=>{:type=>:field, :cost=>"1"},
   "R5"=>{:type=>:town, :cost=>"0", :built=>["red"]},
   "R6"=>{:type=>:field, :cost=>"1"},
   "S0"=>{:type=>:town, :cost=>"2"},
   "S1"=>{:type=>:field, :cost=>"1"},
   "S2"=>{:type=>:field, :cost=>"1"},
   "S3"=>{:type=>:town, :cost=>"0", :built=>["green"]},
   "S4"=>{:type=>:field, :cost=>"1"},
   "S5"=>{:type=>:field, :cost=>"1"}},
 :companies=>
  {:red=>{:started=>true, :money=>0, :shares=>3, :track=>19, :start_hex=>"R5"},
   :blue=>{:started=>true, :money=>0, :shares=>4, :track=>21, :start_hex=>"Q7"},
   :green=>{:started=>true, :money=>0, :shares=>5, :track=>23, :start_hex=>"S3"},
   :yellow=>{:started=>true, :money=>0, :shares=>6, :track=>25, :start_hex=>"Q9"},
   :black=>{:started=>false, :money=>0, :shares=>2, :track=>11, :start_Hex=>"D3"}}}

end
